server:
  port: 8080

spring:
  application:
    name: api-monitoring
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/monitoring}
    username: ${SPRING_R2DBC_USERNAME:postgres}
    password: ${SPRING_R2DBC_PASSWORD:postgres}

openai:
  api-key: ${OPENAI_API_KEY}

monitoring:
  thresholds:
    response-time: ${MONITORING_RESPONSE_TIME_THRESHOLD:1000}
    error-rate: ${MONITORING_ERROR_RATE_THRESHOLD:0.05}
    cpu-usage: ${MONITORING_CPU_USAGE_THRESHOLD:80}
    memory-usage: ${MONITORING_MEMORY_USAGE_THRESHOLD:80}
    network-latency: ${MONITORING_NETWORK_LATENCY_THRESHOLD:200}
  collection:
    interval: ${MONITORING_COLLECTION_INTERVAL:60000}
    window-size: ${MONITORING_WINDOW_SIZE:100}
  anomaly:
    z-score-threshold: ${MONITORING_Z_SCORE_THRESHOLD:3.0}
    failure-threshold: ${MONITORING_FAILURE_THRESHOLD:0.7}

logging:
  level:
    com.banking.monitoring: DEBUG
    org.springframework.web: INFO
    org.springframework.data.r2dbc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always 